In [1]:
import pandas as pd

file_path = "../data/raw/Online Retail.xlsx"

df = pd.read_excel(file_path)

In [ ]:
df["InvoiceNo"].astype(str).str.startswith("C").value_counts()

InvoiceNo
False    532621
True       9288
Name: count, dtype: int64

In [36]:
df["InvoiceNo"].describe()

count     541909
unique     25900
top       573585
freq        1114
Name: InvoiceNo, dtype: int64

In [3]:
duplicates = df[df.duplicated(keep=False)]

duplicates.sort_values(
    ["InvoiceNo", "StockCode", "Quantity"]
).head(30)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
597,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
569,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
611,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
617,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
603,536412,22902,TOTE BAG I LOVE LONDON,7,2010-12-01 11:49:00,2.10,17920.0,United Kingdom

In [7]:
negative_quantity = df[df["Quantity"] < 0]

negative_quantity.shape

(10624, 8)

In [8]:
negative_quantity.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,2010-12-01 14:33:00,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,2010-12-01 14:33:00,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2010-12-01 14:33:00,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,2010-12-01 14:33:00,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,2010-12-01 14:33:00,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,2010-12-01 14:33:00,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,2010-12-01 14:33:00,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,2010-12-01 14:33:00,0.85,12472.0,Germany

In [9]:
negative_quantity["InvoiceNo"].astype(str).str.startswith("C").value_counts()

InvoiceNo
True     9288
False    1336
Name: count, dtype: int64

In [10]:
bad_prices = df[df["UnitPrice"] <= 0]

bad_prices.shape

(2517, 8)

In [11]:
bad_prices.head(30)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
6391,536941,22734,amazon,20,2010-12-03 12:08:00,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,2010-12-03 12:08:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7194,537002,21651,NaN,70,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom

In [12]:
bad_prices["Description"].value_counts().head(20)

Description
check                              159
?                                   47
damages                             45
damaged                             43
found                               25
sold as set on dotcom               20
adjustment                          16
Damaged                             14
FRENCH BLUE METAL DOOR SIGN 1        9
thrown away                          9
Unsaleable, destroyed.               9
amazon                               8
FRENCH BLUE METAL DOOR SIGN 8        8
Found                                8
FRENCH BLUE METAL DOOR SIGN 4        7
FRENCH BLUE METAL DOOR SIGN No       7
OWL DOORSTOP                         7
FRENCH BLUE METAL DOOR SIGN 3        7
RECIPE BOX PANTRY YELLOW DESIGN      7
??                                   7
Name: count, dtype: int64

In [13]:
df["InvoiceNo"].nunique()

25900

In [14]:
df["InvoiceNo"].astype(str).str.startswith("C").sum()

np.int64(9288)

In [15]:
df["InvoiceNo"].astype(str).str.startswith("C").value_counts()

InvoiceNo
False    532621
True       9288
Name: count, dtype: int64

In [36]:
customerIDNull = df[df["CustomerID"].isna()]
customerIDNull.head(50)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1448,536544,21791,VINTAGE HEADS AND TAILS CARD GAME,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1449,536544,21801,CHRISTMAS TREE DECORATION WITH BELL,10,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1450,536544,21802,CHRISTMAS TREE HEART DECORATION,9,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1451,536544,21803,CHRISTMAS TREE STAR DECORATION,11,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1452,536544,21809,CHRISTMAS HANGING TREE WITH BELL,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1453,536544,21810,CHRISTMAS HANGING STAR WITH BELL,3,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1454,536544,21811,CHRISTMAS HANGING HEART WITH BELL,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1455,536544,21821,GLITTER STAR GARLAND WITH BELLS,1,2010-12-01 14:32:00,7.62,NaN,United Kingdom
1456,536544,21822,GLITTER CHRISTMAS TREE WITH BELLS,1,2010-12-01 14:32:00,4.21,NaN,United Kingdom
1457,536544,21823,PAINTED METAL HEART WITH HOLLY BELL,2,2010-12-01 14:32:00,2.98,NaN,United Kingdom
1458,536544,21844,RED RETROSPOT MUG,2,2010-12-01 14:32:00,5.91,NaN,United Kingdom
1459,536544,21851,LILAC DIAMANTE PEN IN GIFT BOX,1,2010-12-01 14:32:00,4.21,NaN,United Kingdom
1460,536544,21870,I CAN ONLY PLEASE ONE PERSON MUG,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1461,536544,21871,SAVE THE PLANET MUG,5,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1462,536544,21874,GIN AND TONIC MUG,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1463,536544,21879,HEARTS GIFT TAPE,1,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1464,536544,21884,CAKES AND BOWS GIFT TAPE,1,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1465,536544,21888,BINGO SET,1,2010-12-01 14:32:00,7.62,NaN,United Kingdom
1466,536544,21889,WOODEN BOX OF DOMINOES,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1467,536544,21892,TRADITIONAL WOODEN CATCH CUP GAME,3,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1468,536544,21894,POTTING SHED SEED ENVELOPES,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1469,536544,21911,GARDEN METAL SIGN,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1470,536544,21912,VINTAGE SNAKES & LADDERS,3,2010-12-01 14:32:00,7.62,NaN,United Kingdom
1471,536544,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2010-12-01 14:32:00,7.62,NaN,United Kingdom
1472,536544,21914,BLUE HARMONICA IN BOX,3,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1473,536544,21915,RED HARMONICA IN BOX,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1474,536544,21922,UNION STRIPE WITH FRINGE HAMMOCK,2,2010-12-01 14:32:00,16.98,NaN,United Kingdom
1475,536544,21928,JUMBO BAG SCANDINAVIAN PAISLEY,1,2010-12-01 14:32:00,4.21,NaN,United Kingdom
1476,536544,21935,SUKI SHOULDER BAG,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1477,536544,21942,SKULLS DESIGN FLANNEL,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1478,536544,21944,KITTENS DESIGN FLANNEL,1,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1479,536544,21949,SET OF 6 STRAWBERRY CHOPSTICKS,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1480,536544,21975,PACK OF 60 DINOSAUR CAKE CASES,1,2010-12-01 14:32:00,1.28,NaN,United Kingdom
1481,536544,21977,PACK OF 60 PINK PAISLEY CAKE CASES,1,2010-12-01 14:32:00,1.28,NaN,United Kingdom
1482,536544,21982,PACK OF 12 SUKI TISSUES,1,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1483,536544,21990,MODERN FLORAL STATIONERY SET,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1484,536544,21991,BOHEMIAN COLLAGE STATIONERY SET,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1485,536544,21992,VINTAGE PAISLEY STATIONERY SET,6,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1486,536544,21993,FLORAL FOLK STATIONERY SET,4,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1487,536544,22037,ROBOT BIRTHDAY CARD,1,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1488,536544,22043,CHRISTMAS CARD SCREEN PRINT,1,2010-12-01 14:32:00,0.43,NaN,United Kingdom
1489,536544,22064,PINK DOUGHNUT TRINKET POT,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1490,536544,22065,CHRISTMAS PUDDING TRINKET POT,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom
1491,536544,22067,CHOC TRUFFLE GOLD TRINKET POT,1,2010-12-01 14:32:00,3.36,NaN,United Kingdom

In [23]:
len(customerIDNull)

135080

In [31]:
lowPrice = df[df["Quantity"] <= 0 ]
lowPrice.head(50)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,2010-12-01 14:33:00,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,2010-12-01 14:33:00,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2010-12-01 14:33:00,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,2010-12-01 14:33:00,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,2010-12-01 14:33:00,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,2010-12-01 14:33:00,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,2010-12-01 14:33:00,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,2010-12-01 14:33:00,0.85,12472.0,Germany
1981,C536548,22077,6 RIBBONS RUSTIC CHARM,-6,2010-12-01 14:33:00,1.65,12472.0,Germany
1982,C536548,22631,CIRCUS PARADE LUNCH BOX,-1,2010-12-01 14:33:00,1.95,12472.0,Germany
1983,C536548,22168,ORGANISER WOOD ANTIQUE WHITE,-2,2010-12-01 14:33:00,8.50,12472.0,Germany
1984,C536548,21218,RED SPOTTY BISCUIT TIN,-3,2010-12-01 14:33:00,3.75,12472.0,Germany
1985,C536548,20957,PORCELAIN HANGING BELL SMALL,-1,2010-12-01 14:33:00,1.45,12472.0,Germany
1986,C536548,22580,ADVENT CALENDAR GINGHAM SACK,-4,2010-12-01 14:33:00,5.95,12472.0,Germany
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.00,NaN,United Kingdom
3170,C536606,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-2,2010-12-02 09:10:00,2.95,14092.0,United Kingdom
3338,C536622,22752,SET 7 BABUSHKA NESTING BOXES,-2,2010-12-02 10:37:00,8.50,12471.0,Germany
3410,C536625,22839,3 TIER CAKE TIN GREEN AND CREAM,-2,2010-12-02 10:46:00,14.95,14766.0,United Kingdom
3693,C536642,21463,MIRRORED DISCO BALL,-1,2010-12-02 11:56:00,5.95,14390.0,United Kingdom
3911,C536734,22780,LIGHT GARLAND BUTTERFILES PINK,-4,2010-12-02 12:50:00,4.25,16042.0,United Kingdom
3912,C536734,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,-1,2010-12-02 12:50:00,7.95,16042.0,United Kingdom
3919,C536737,22798,ANTIQUE GLASS DRESSING TABLE POT,-2,2010-12-02 13:05:00,2.95,15922.0,United Kingdom
4287,C536757,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,-9360,2010-12-02 14:23:00,0.03,15838.0,United Kingdom
4288,C536758,21314,SMALL GLASS HEART TRINKET POT,-1,2010-12-02 14:25:00,2.10,13767.0,United Kingdom
4306,C536760,22175,PINK OWL SOFT TOY,-1,2010-12-02 14:29:00,2.95,17547.0,United Kingdom
4307,C536760,22273,FELTCRAFT DOLL MOLLY,-3,2010-12-02 14:29:00,2.95,17547.0,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.00,NaN,United Kingdom
4836,C536807,22501,PICNIC BASKET WICKER LARGE,-2,2010-12-02 16:45:00,9.95,15834.0,United Kingdom
4837,C536807,22778,GLASS CLOCHE SMALL,-1,2010-12-02 16:45:00,3.95,15834.0,United Kingdom
4853,C536812,22578,WOODEN STAR CHRISTMAS SCANDINAVIAN,-36,2010-12-02 16:58:00,0.85,16546.0,United Kingdom
4854,C536812,22574,HEART WOODEN CHRISTMAS DECORATION,-192,2010-12-02 16:58:00,0.72,16546.0,United Kingdom
4855,C536812,22593,CHRISTMAS GINGHAM STAR,-144,2010-12-02 16:58:00,0.72,16546.0,United Kingdom
4856,C536812,22595,CHRISTMAS GINGHAM HEART,-144,2010-12-02 16:58:00,0.72,16546.0,United Kingdom
4857,C536812,22588,CARD HOLDER GINGHAM HEART,-192,2010-12-02 16:58:00,2.10,16546.0,United Kingdom
4858,C536812,22130,PARTY CONE CHRISTMAS DECORATION,-144,2010-12-02 16:58:00,0.72,16546.0,United Kingdom
4876,C536814,21527,RED RETROSPOT TRADITIONAL TEAPOT,-2,2010-12-02 17:03:00,7.95,13958.0,United Kingdom
4877,C536814,72799E,IVORY PILLAR CANDLE SILVER FLOCK,-6,2010-12-02 17:03:00,2.95,13958.0,United Kingdom
4878,C536814,85066,CREAM SWEETHEART MINI CHEST,-2,2010-12-02 17:03:00,12.75,13958.0,United Kingdom

In [38]:
negative_qty = df[df["Quantity"] < 0]

negative_qty[
    ~negative_qty["InvoiceNo"].astype(str).str.startswith("C")
].head(30)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,2010-12-03 15:39:00,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7208,537016,21836,NaN,-15,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7209,537017,47556B,NaN,-69,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7210,537018,84562A,NaN,-3,2010-12-03 15:42:00,0.0,NaN,United Kingdom
7211,537019,37474,NaN,-15,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7212,537020,21807,NaN,-30,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7213,537021,21011,NaN,-20,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7291,537027,18098C,NaN,-140,2010-12-03 16:36:00,0.0,NaN,United Kingdom
7292,537028,21696,NaN,-320,2010-12-03 16:36:00,0.0,NaN,United Kingdom
7293,537029,37476,NaN,-6,2010-12-03 16:37:00,0.0,NaN,United Kingdom
7313,537032,21275,?,-30,2010-12-03 16:50:00,0.0,NaN,United Kingdom

In [39]:
negative_qty[
    ~negative_qty["InvoiceNo"].astype(str).str.startswith("C")
].shape

(1336, 8)

In [44]:
cancellations = df[
    df["InvoiceNo"].astype(str).str.startswith("C")
]

cancellations[
    cancellations["Quantity"] >= 0
].head(30)

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [41]:
cancellations[
    cancellations["Quantity"] >= 0
].shape

(0, 8)

In [5]:
zero_price = df[df["UnitPrice"] == 0]

zero_price["Description"].value_counts().head(30)

Description
check                              159
?                                   47
damages                             45
damaged                             43
found                               25
sold as set on dotcom               20
adjustment                          16
Damaged                             14
FRENCH BLUE METAL DOOR SIGN 1        9
thrown away                          9
Unsaleable, destroyed.               9
amazon                               8
FRENCH BLUE METAL DOOR SIGN 8        8
Found                                8
FRENCH BLUE METAL DOOR SIGN 4        7
FRENCH BLUE METAL DOOR SIGN No       7
OWL DOORSTOP                         7
FRENCH BLUE METAL DOOR SIGN 3        7
RECIPE BOX PANTRY YELLOW DESIGN      7
??                                   7
Amazon                               7
FRENCH BLUE METAL DOOR SIGN 7        6
FRENCH BLUE METAL DOOR SIGN 5        6
FRENCH BLUE METAL DOOR SIGN 6        6
RED KITCHEN SCALES                   6
FRENCH BLUE METAL DOOR SIGN 9        6
MINT KITCHEN SCALES                  6
dotcom                               6
Manual                               6
BOX OF 24 COCKTAIL PARASOLS          5
Name: count, dtype: int64

In [6]:
# duplicate_rows = df[df.duplicated(keep=False)].copy()

# duplicate_rows.sort_values(
#     ["InvoiceNo", "StockCode", "Description"]
# ).head(50)

zero_price["StockCode"].value_counts().head(30)

StockCode
23084     16
35965     13
20713     11
22501     10
22676      9
22627      9
22084      9
22683      8
21116      8
46000S     8
82583      8
22734      7
22679      7
22686      7
22625      7
79321      7
22678      7
22666      7
23348      7
21830      7
21181      7
22682      6
22680      6
22681      6
22524      6
22502      6
46000M     6
85123A     6
22684      6
22665      6
Name: count, dtype: int64

In [7]:
zero_price["InvoiceNo"].astype(str).str.startswith("C").value_counts()

InvoiceNo
False    2515
Name: count, dtype: int64

In [8]:
missing_customer = df[df["CustomerID"].isna()]
known_customer = df[df["CustomerID"].notna()]

In [9]:
missing_customer["Country"].value_counts().head(10)

Country
United Kingdom    133600
EIRE                 711
Hong Kong            288
Unspecified          202
Switzerland          125
France                66
Israel                47
Portugal              39
Bahrain                2
Name: count, dtype: int64

In [10]:
known_customer["Country"].value_counts().head(10)

Country
United Kingdom    361878
Germany             9495
France              8491
EIRE                7485
Spain               2533
Netherlands         2371
Belgium             2069
Switzerland         1877
Portugal            1480
Australia           1259
Name: count, dtype: int64

In [11]:
missing_customer["Quantity"].describe()

count    135080.000000
mean          1.995573
std          66.696153
min       -9600.000000
25%           1.000000
50%           1.000000
75%           3.000000
max        5568.000000
Name: Quantity, dtype: float64

In [12]:
known_customer["Quantity"].describe()

count    406829.000000
mean         12.061303
std         248.693370
min      -80995.000000
25%           2.000000
50%           5.000000
75%          12.000000
max       80995.000000
Name: Quantity, dtype: float64

In [13]:
missing_customer["InvoiceNo"].astype(str).str.startswith("C").value_counts()

InvoiceNo
False    134697
True        383
Name: count, dtype: int64

In [14]:
duplicate_rows = df[df.duplicated(keep=False)].copy()

duplicate_rows.sort_values(
    ["InvoiceNo", "StockCode", "Description"]
).head(50)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
597,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
569,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
611,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
617,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
603,536412,22902,TOTE BAG I LOVE LONDON,7,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
605,536412,22902,TOTE BAG I LOVE LONDON,7,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
615,536412,85184C,S/4 VALENTINE DECOUPAGE HEART BOX,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
620,536412,85184C,S/4 VALENTINE DECOUPAGE HEART BOX,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
757,536446,21651,HANGING GLASS ETCHED TEALIGHT,6,2010-12-01 12:15:00,1.65,15983.0,United Kingdom
758,536446,21651,HANGING GLASS ETCHED TEALIGHT,6,2010-12-01 12:15:00,1.65,15983.0,United Kingdom
808,536464,21992,VINTAGE PAISLEY STATIONERY SET,1,2010-12-01 12:23:00,2.95,17968.0,United Kingdom
852,536464,21992,VINTAGE PAISLEY STATIONERY SET,1,2010-12-01 12:23:00,2.95,17968.0,United Kingdom
829,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 12:23:00,2.10,17968.0,United Kingdom
831,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 12:23:00,2.10,17968.0,United Kingdom
859,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 12:23:00,2.10,17968.0,United Kingdom
813,536464,22945,CHRISTMAS METAL TAGS ASSORTED,6,2010-12-01 12:23:00,0.85,17968.0,United Kingdom
835,536464,22945,CHRISTMAS METAL TAGS ASSORTED,6,2010-12-01 12:23:00,0.85,17968.0,United Kingdom
890,536488,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,1,2010-12-01 12:31:00,2.55,17897.0,United Kingdom
891,536488,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,1,2010-12-01 12:31:00,2.55,17897.0,United Kingdom
1036,536522,21121,SET/10 RED POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012.0,United Kingdom
1061,536522,21121,SET/10 RED POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012.0,United Kingdom
1062,536522,21122,SET/10 PINK POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012.0,United Kingdom
1067,536522,21122,SET/10 PINK POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012.0,United Kingdom
1136,536528,22411,JUMBO SHOPPER VINTAGE RED PAISLEY,1,2010-12-01 13:17:00,1.95,15525.0,United Kingdom
1169,536528,22411,JUMBO SHOPPER VINTAGE RED PAISLEY,1,2010-12-01 13:17:00,1.95,15525.0,United Kingdom

In [4]:
negative_non_c = df[
    (df["Quantity"] < 0) &
    (~df["InvoiceNo"].astype(str).str.startswith("C"))
]

negative_non_c.head(30)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,2010-12-03 15:39:00,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7208,537016,21836,NaN,-15,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7209,537017,47556B,NaN,-69,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7210,537018,84562A,NaN,-3,2010-12-03 15:42:00,0.0,NaN,United Kingdom
7211,537019,37474,NaN,-15,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7212,537020,21807,NaN,-30,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7213,537021,21011,NaN,-20,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7291,537027,18098C,NaN,-140,2010-12-03 16:36:00,0.0,NaN,United Kingdom
7292,537028,21696,NaN,-320,2010-12-03 16:36:00,0.0,NaN,United Kingdom
7293,537029,37476,NaN,-6,2010-12-03 16:37:00,0.0,NaN,United Kingdom
7313,537032,21275,?,-30,2010-12-03 16:50:00,0.0,NaN,United Kingdom

In [5]:
negative_non_c["Description"].value_counts().head(30)

Description
check                           120
damages                          45
damaged                          42
?                                41
sold as set on dotcom            20
Damaged                          14
thrown away                       9
Unsaleable, destroyed.            9
??                                7
damages?                          5
wet damaged                       5
ebay                              5
smashed                           4
missing                           3
CHECK                             3
wet pallet                        3
Dotcom sales                      2
reverse 21/5/10 adjustment        2
counted                           2
crushed                           2
wet/rusty                         2
printing smudges/thrown away      2
sold as 1                         2
?missing                          2
incorrect stock entry.            2
stock check                       2
adjustment                        2
damages wax                       2
wet rusty                         2
rusty throw away                  2
Name: count, dtype: int64

In [6]:
negative_non_c["StockCode"].value_counts().head(30)

StockCode
85175     5
21830     5
85172     4
22719     4
82494L    4
72802C    4
21161     3
22162     3
22034     3
20966     3
22423     3
20892     3
46000S    3
22501     3
22837     3
84631     3
35954     3
84406B    3
22114     3
21621     3
40016     3
85049D    3
20713     3
85017A    3
20774     3
21135     3
79163     3
23084     3
21033     3
72802B    3
Name: count, dtype: int64

In [7]:
negative_non_c["UnitPrice"].describe()

count    1336.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: UnitPrice, dtype: float64

In [8]:
negative_non_c["CustomerID"].isna().value_counts()

CustomerID
True    1336
Name: count, dtype: int64

In [9]:
cancellations = df[
    df["InvoiceNo"].astype(str).str.startswith("C")
]

cancellations.shape

(9288, 8)

In [10]:
cancellations["CustomerID"].isna().value_counts()

CustomerID
False    8905
True      383
Name: count, dtype: int64

In [11]:
cancellations["UnitPrice"].describe()

count     9288.000000
mean        48.393661
std        666.600430
min          0.010000
25%          1.450000
50%          2.950000
75%          5.950000
max      38970.000000
Name: UnitPrice, dtype: float64

In [12]:
cancellations["Description"].value_counts().head(30)

Description
Manual                                 244
REGENCY CAKESTAND 3 TIER               181
POSTAGE                                126
JAM MAKING SET WITH JARS                87
Discount                                77
SET OF 3 CAKE TINS PANTRY DESIGN        74
SAMPLES                                 61
STRAWBERRY CERAMIC TRINKET BOX          55
ROSES REGENCY TEACUP AND SAUCER         54
RECIPE BOX PANTRY YELLOW DESIGN         47
WOOD 2 DRAWER CABINET WHITE FINISH      45
JUMBO BAG RED RETROSPOT                 44
LUNCH BAG RED RETROSPOT                 44
RED RETROSPOT CAKE STAND                42
WHITE HANGING HEART T-LIGHT HOLDER      42
GREEN REGENCY TEACUP AND SAUCER         42
SMALL GLASS HEART TRINKET POT           40
SET OF 3 REGENCY CAKE TINS              37
POPCORN HOLDER                          36
SILVER HANGING T-LIGHT HOLDER           35
PINK REGENCY TEACUP AND SAUCER          35
SET OF TEA COFFEE SUGAR TINS PANTRY     35
SET/5 RED RETROSPOT LID GLASS BOWLS     34
CLASSIC GLASS COOKIE JAR                34
ALARM CLOCK BAKELIKE RED                33
AMAZON FEE                              32
NATURAL SLATE CHALKBOARD LARGE          32
BREAD BIN DINER STYLE IVORY             31
GUMBALL COAT RACK                       30
HANGING HEART JAR T-LIGHT HOLDER        30
Name: count, dtype: int64

In [2]:
negative_price = df[df["UnitPrice"] < 0]

negative_price.shape

(2, 8)

In [3]:
negative_price["Description"].value_counts().head(30)

Description
Adjust bad debt    2
Name: count, dtype: int64

In [4]:
negative_price["InvoiceNo"].astype(str).str.startswith("C").value_counts()

InvoiceNo
False    2
Name: count, dtype: int64

In [5]:
negative_price[["InvoiceNo", "StockCode", "Description",
                "Quantity", "UnitPrice", "CustomerID", "Country"]].head(30)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,-11062.06,NaN,United Kingdom

In [6]:
negative_price["CustomerID"].isna().value_counts()

CustomerID
True    2
Name: count, dtype: int64