In [1]:
import pandas as pd
file_path = "../data/raw/Online Retail.xlsx"

df = pd.read_excel(file_path)

In [3]:
clean_df = df.copy()

In [4]:
print("Rows:", clean_df.shape[0])
print("Columns:", clean_df.shape[1])
print("Exact duplicates:", clean_df.duplicated().sum())

Rows: 541909
Columns: 8
Exact duplicates: 5268

In [5]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [6]:
clean_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [7]:
before = clean_df.shape[0]

clean_df = clean_df.drop_duplicates().copy()

after = clean_df.shape[0]

print("Rows before:", before)
print("Rows after:", after)
print("Rows removed:", before - after)
print("Remaining duplicates:", clean_df.duplicated().sum())

Rows before: 541909
Rows after: 536641
Rows removed: 5268
Remaining duplicates: 0

In [8]:
clean_df.columns = (
    clean_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [9]:
print(clean_df.columns.tolist())

['invoiceno', 'stockcode', 'description', 'quantity', 'invoicedate', 'unitprice', 'customerid', 'country']

In [10]:
clean_df.columns = [
    "invoice_no",
    "stock_code",
    "description",
    "quantity",
    "invoice_date",
    "unit_price",
    "customer_id",
    "country"
]

In [11]:
print(clean_df.columns.tolist())

['invoice_no', 'stock_code', 'description', 'quantity', 'invoice_date', 'unit_price', 'customer_id', 'country']

In [12]:
clean_df.dtypes

invoice_no              object
stock_code              object
description             object
quantity                 int64
invoice_date    datetime64[us]
unit_price             float64
customer_id            float64
country                    str
dtype: object

In [13]:
clean_df.info()

<class 'pandas.DataFrame'>
Index: 536641 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice_no    536641 non-null  object
 1   stock_code    536641 non-null  object
 2   description   535187 non-null  object
 3   quantity      536641 non-null  int64
 4   invoice_date  536641 non-null  datetime64[us]
 5   unit_price    536641 non-null  float64
 6   customer_id   401604 non-null  float64
 7   country       536641 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 36.8+ MB

In [14]:
clean_df[[
    "quantity",
    "invoice_date",
    "unit_price",
    "customer_id"
]].head()

   quantity        invoice_date  unit_price  customer_id
0         6 2010-12-01 08:26:00        2.55      17850.0
1         6 2010-12-01 08:26:00        3.39      17850.0
2         8 2010-12-01 08:26:00        2.75      17850.0
3         6 2010-12-01 08:26:00        3.39      17850.0
4         6 2010-12-01 08:26:00        3.39      17850.0

In [15]:
clean_df["customer_id"] = clean_df["customer_id"].astype("Int64")

In [16]:
clean_df.dtypes

invoice_no              object
stock_code              object
description             object
quantity                 int64
invoice_date    datetime64[us]
unit_price             float64
customer_id              Int64
country                    str
dtype: object

In [17]:
print("Missing Customer IDs:", clean_df["customer_id"].isna().sum())
print("Unique Customer IDs:", clean_df["customer_id"].nunique())

Missing Customer IDs: 135037
Unique Customer IDs: 4372

In [18]:
print("Minimum quantity:", clean_df["quantity"].min())
print("Maximum quantity:", clean_df["quantity"].max())
print("Negative quantity rows:", (clean_df["quantity"] < 0).sum())
print("Zero quantity rows:", (clean_df["quantity"] == 0).sum())

Minimum quantity: -80995
Maximum quantity: 80995
Negative quantity rows: 10587
Zero quantity rows: 0

In [19]:
print("Minimum unit price:", clean_df["unit_price"].min())
print("Maximum unit price:", clean_df["unit_price"].max())
print("Negative price rows:", (clean_df["unit_price"] < 0).sum())
print("Zero price rows:", (clean_df["unit_price"] == 0).sum())

Minimum unit price: -11062.06
Maximum unit price: 38970.0
Negative price rows: 2
Zero price rows: 2510

In [20]:
print("Earliest invoice date:", clean_df["invoice_date"].min())
print("Latest invoice date:", clean_df["invoice_date"].max())
print("Missing invoice dates:", clean_df["invoice_date"].isna().sum())

Earliest invoice date: 2010-12-01 08:26:00
Latest invoice date: 2011-12-09 12:50:00
Missing invoice dates: 0

In [21]:
clean_df[clean_df["unit_price"] < 0]

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,<NA>,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,<NA>,United Kingdom

In [22]:
clean_df["transaction_type"] = "SALE"

clean_df.loc[
    clean_df["unit_price"] < 0,
    "transaction_type"
] = "BAD_DEBT_ADJUSTMENT"

clean_df.loc[
    (clean_df["quantity"] < 0) &
    (~clean_df["invoice_no"].astype(str).str.startswith("C")),
    "transaction_type"
] = "INVENTORY_ADJUSTMENT"

clean_df.loc[
    clean_df["invoice_no"].astype(str).str.startswith("C"),
    "transaction_type"
] = "CANCELLATION"

In [23]:
clean_df["transaction_type"].value_counts()

transaction_type
SALE                    526052
CANCELLATION              9251
INVENTORY_ADJUSTMENT      1336
BAD_DEBT_ADJUSTMENT          2
Name: count, dtype: int64

In [24]:
pd.crosstab(
    clean_df["transaction_type"],
    clean_df["quantity"] < 0
)

quantity               False  True
transaction_type
BAD_DEBT_ADJUSTMENT        2      0
CANCELLATION               0   9251
INVENTORY_ADJUSTMENT       0   1336
SALE                  526052      0

In [25]:
clean_df[clean_df["transaction_type"] == "BAD_DEBT_ADJUSTMENT"]

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,transaction_type
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,<NA>,United Kingdom,BAD_DEBT_ADJUSTMENT
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,<NA>,United Kingdom,BAD_DEBT_ADJUSTMENT

In [26]:
clean_df[clean_df["transaction_type"] == "BAD_DEBT_ADJUSTMENT"]

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,transaction_type
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,<NA>,United Kingdom,BAD_DEBT_ADJUSTMENT
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,<NA>,United Kingdom,BAD_DEBT_ADJUSTMENT

In [27]:
clean_df.loc[
    clean_df["unit_price"] == 0,
    "transaction_type"
].value_counts()

transaction_type
INVENTORY_ADJUSTMENT    1336
SALE                    1174
Name: count, dtype: int64

In [28]:
clean_df.loc[
    clean_df["unit_price"] == 0,
    ["description", "stock_code", "quantity", "transaction_type"]
].head(30)

     description stock_code  quantity      transaction_type
622          NaN      22139        56                  SALE
1970         NaN      21134         1                  SALE
1971         NaN      22145         1                  SALE
1972         NaN      37509         1                  SALE
1987         NaN     85226A         1                  SALE
1988         NaN      85044         1                  SALE
2024         NaN      20950         1                  SALE
2025         NaN      37461         3                  SALE
2026         NaN      84670        23                  SALE
2406         NaN      21777       -10  INVENTORY_ADJUSTMENT
4347         NaN     84952C       -38  INVENTORY_ADJUSTMENT
4348         NaN     84952C        19                  SALE
6391      amazon      22734        20                  SALE
6392      amazon      22139        15                  SALE
7187         NaN      35951        57                  SALE
7188         NaN      22712       -20  INVENTORY_ADJUSTMENT
7189         NaN      22028       -20  INVENTORY_ADJUSTMENT
7190         NaN      85067        -6  INVENTORY_ADJUSTMENT
7191         NaN      21421       110                  SALE
7192         NaN      21414       -22  INVENTORY_ADJUSTMENT
7193         NaN      21653        -6  INVENTORY_ADJUSTMENT
7194         NaN      21651        70                  SALE
7195         NaN      85126        -2  INVENTORY_ADJUSTMENT
7196         NaN      21814       -30  INVENTORY_ADJUSTMENT
7197         NaN      21692       -70  INVENTORY_ADJUSTMENT
7198         NaN      21648      -130  INVENTORY_ADJUSTMENT
7199         NaN      21172       -80  INVENTORY_ADJUSTMENT
7200         NaN      21161      -120  INVENTORY_ADJUSTMENT
7201         NaN     84534B       -80  INVENTORY_ADJUSTMENT
7202         NaN      22162       -40  INVENTORY_ADJUSTMENT

In [29]:
zero_price = clean_df["unit_price"] == 0

print("Zero-price rows:", zero_price.sum())
print(
    "Zero-price rows with Customer ID:",
    clean_df.loc[zero_price, "customer_id"].notna().sum()
)
print(
    "Zero-price rows without Customer ID:",
    clean_df.loc[zero_price, "customer_id"].isna().sum()
)

Zero-price rows: 2510
Zero-price rows with Customer ID: 40
Zero-price rows without Customer ID: 2470

In [30]:
clean_df["revenue"] = clean_df["quantity"] * clean_df["unit_price"]

In [31]:
clean_df[
    ["quantity", "unit_price", "transaction_type", "revenue"]
].head(10)

   quantity  unit_price transaction_type  revenue
0         6        2.55             SALE    15.30
1         6        3.39             SALE    20.34
2         8        2.75             SALE    22.00
3         6        3.39             SALE    20.34
4         6        3.39             SALE    20.34
5         2        7.65             SALE    15.30
6         6        4.25             SALE    25.50
7         6        1.85             SALE    11.10
8         6        1.85             SALE    11.10
9        32        1.69             SALE    54.08

In [32]:
clean_df["sales_revenue"] = clean_df["revenue"].where(
    clean_df["transaction_type"] == "SALE",
    0
)

In [33]:
print("Total transaction value:", clean_df["revenue"].sum())
print("Total sales revenue:", clean_df["sales_revenue"].sum())
print(
    "Revenue from cancellations:",
    clean_df.loc[
        clean_df["transaction_type"] == "CANCELLATION",
        "revenue"
    ].sum()
)
print(
    "Revenue from inventory adjustments:",
    clean_df.loc[
        clean_df["transaction_type"] == "INVENTORY_ADJUSTMENT",
        "revenue"
    ].sum()
)
print(
    "Revenue from bad-debt adjustments:",
    clean_df.loc[
        clean_df["transaction_type"] == "BAD_DEBT_ADJUSTMENT",
        "revenue"
    ].sum()
)

Total transaction value: 9726006.954
Total sales revenue: 10642110.804000001
Revenue from cancellations: -893979.73
Revenue from inventory adjustments: 0.0
Revenue from bad-debt adjustments: -22124.12

In [34]:
clean_df[
    ["transaction_type", "quantity", "unit_price", "revenue", "sales_revenue"]
].tail(10)

       transaction_type  quantity  unit_price  revenue  sales_revenue
541899             SALE         4        3.75    15.00          15.00
541900             SALE         4        3.75    15.00          15.00
541901             SALE         8        1.95    15.60          15.60
541902             SALE        12        1.95    23.40          23.40
541903             SALE         4        4.15    16.60          16.60
541904             SALE        12        0.85    10.20          10.20
541905             SALE         6        2.10    12.60          12.60
541906             SALE         4        4.15    16.60          16.60
541907             SALE         4        4.15    16.60          16.60
541908             SALE         3        4.95    14.85          14.85

In [35]:
print(
    "Missing descriptions:",
    clean_df["description"].isna().sum()
)

print(
    "Missing description percentage:",
    round(
        clean_df["description"].isna().mean() * 100,
        2
    ),
    "%"
)

Missing descriptions: 1454
Missing description percentage: 0.27 %

In [36]:
clean_df.loc[
    clean_df["description"].isna(),
    "transaction_type"
].value_counts()

transaction_type
INVENTORY_ADJUSTMENT    862
SALE                    592
Name: count, dtype: int64

In [37]:
clean_df.loc[
    clean_df["description"].isna(),
    ["stock_code", "quantity", "unit_price", "transaction_type"]
].head(30)

     stock_code  quantity  unit_price      transaction_type
622       22139        56         0.0                  SALE
1970      21134         1         0.0                  SALE
1971      22145         1         0.0                  SALE
1972      37509         1         0.0                  SALE
1987     85226A         1         0.0                  SALE
1988      85044         1         0.0                  SALE
2024      20950         1         0.0                  SALE
2025      37461         3         0.0                  SALE
2026      84670        23         0.0                  SALE
2406      21777       -10         0.0  INVENTORY_ADJUSTMENT
4347     84952C       -38         0.0  INVENTORY_ADJUSTMENT
4348     84952C        19         0.0                  SALE
7187      35951        57         0.0                  SALE
7188      22712       -20         0.0  INVENTORY_ADJUSTMENT
7189      22028       -20         0.0  INVENTORY_ADJUSTMENT
7190      85067        -6         0.0  INVENTORY_ADJUSTMENT
7191      21421       110         0.0                  SALE
7192      21414       -22         0.0  INVENTORY_ADJUSTMENT
7193      21653        -6         0.0  INVENTORY_ADJUSTMENT
7194      21651        70         0.0                  SALE
7195      85126        -2         0.0  INVENTORY_ADJUSTMENT
7196      21814       -30         0.0  INVENTORY_ADJUSTMENT
7197      21692       -70         0.0  INVENTORY_ADJUSTMENT
7198      21648      -130         0.0  INVENTORY_ADJUSTMENT
7199      21172       -80         0.0  INVENTORY_ADJUSTMENT
7200      21161      -120         0.0  INVENTORY_ADJUSTMENT
7201     84534B       -80         0.0  INVENTORY_ADJUSTMENT
7202      22162       -40         0.0  INVENTORY_ADJUSTMENT
7203      22139        -5         0.0  INVENTORY_ADJUSTMENT
7204      21535       -12         0.0  INVENTORY_ADJUSTMENT

In [38]:
print("Exact duplicates:", clean_df.duplicated().sum())

Exact duplicates: 0

In [39]:
clean_df.isna().sum()

invoice_no               0
stock_code               0
description           1454
quantity                 0
invoice_date             0
unit_price               0
customer_id         135037
country                  0
transaction_type         0
revenue                  0
sales_revenue            0
dtype: int64

In [40]:
clean_df["transaction_type"].value_counts()

transaction_type
SALE                    526052
CANCELLATION              9251
INVENTORY_ADJUSTMENT      1336
BAD_DEBT_ADJUSTMENT          2
Name: count, dtype: int64

In [41]:
clean_df[
    [
        "invoice_no",
        "quantity",
        "unit_price",
        "customer_id",
        "transaction_type",
        "revenue",
        "sales_revenue"
    ]
].head()

,invoice_no,quantity,unit_price,customer_id,transaction_type,revenue,sales_revenue
0,536365,6,2.55,17850,SALE,15.30,15.30
1,536365,6,3.39,17850,SALE,20.34,20.34
2,536365,8,2.75,17850,SALE,22.00,22.00
3,536365,6,3.39,17850,SALE,20.34,20.34
4,536365,6,3.39,17850,SALE,20.34,20.34

In [42]:
print("Final rows:", clean_df.shape[0])
print("Final columns:", clean_df.shape[1])
print("\nColumns:")
print(clean_df.columns.tolist())

Final rows: 536641
Final columns: 11

Columns:
['invoice_no', 'stock_code', 'description', 'quantity', 'invoice_date', 'unit_price', 'customer_id', 'country', 'transaction_type', 'revenue', 'sales_revenue']

In [43]:
output_path = "../data/processed/online_retail_clean.csv"

clean_df.to_csv(output_path, index=False)

print("Clean dataset saved to:", output_path)

Clean dataset saved to: ../data/processed/online_retail_clean.csv